language: scala
scala:
- 2.12.6
jdk: oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt assembly

deploy:
  provider: heroku
  api_key:
    secure: tGRRt7VHBVFlOhI9glrzAWTQIoEIJ0S6KzaEQxwmEO7c0FRmZgeHWl5RSmamGPshMNsIODrcT2geEZETyAh4hMMAYoh4PTg8+r56v5OJVoIqxDAkIeBRF01fDJz+8bfb4vbC5tL8/katS8khp92eUVyu5QRHiqP5JNej+TM/6XK5Acn9k9oayVDSlfB7GpT7n3MIjY4rsXdbVQ2pqIhcsOiYFPL7iX+K61tO3BW3RGNoO3L1dj5g799qo2qOnIl1p8T5OwlyKbJaGBO5nfGDxgd0EIcLLsWGbK8yEskimfhSpDXOHpBzavRUHGvvaOxIHNgJpQg5XyQXIJEELPmSkPKY7/R9IbAvfeoS7wF48C5aZhL9zs1PNR5qqF4Mlb/jQWdydINSs4HCEWHFqXCpKvYFEk+gRA5P9lvCPd6B/nTbryD4IH7RGVVUWRJ9b1bzheugSIxyb2R08olURO0FqJuxl0/6e0wKZCZr+QFN937e7eSRYBtIEQiqFejkqdMSjl26IiGjJb276jjjQr5tQFMmSFFmHzHYpdLn9x7yUU08B26A4sfhRXGPSQX5uFBVfYNwFP87F01V/wHHLvA7lpAgeNrpGVkLYLtzMaxLq7WjMkk9kwmBqlT6T5i2iCj0k6+GUYLHs0/RuPe2Kz/uefDZ9Lc7pKbHrWrkPXTq2+k=
  app: wod-watcher
  on:
    repo: klkelley/wod-watcher
    branch: master
